export const data = {
	uz: [
		{
			id: 1,
			title: 'QASRI',
			caption: 'CHINAKAM SHINAMLIK',
			images: [
				'/images/header-carousel/slide-1.webp',
				'/images/header-carousel/slide-1.jpg',
				'/images/header-carousel/slide-1-1360.webp',
				'/images/header-carousel/slide-1-1360.jpg',
				'/images/header-carousel/slide-1-1200.webp',
				'/images/header-carousel/slide-1-1200.jpg',
				'/images/header-carousel/slide-1-992.webp',
				'/images/header-carousel/slide-1-992.jpg',
				'/images/header-carousel/slide-1-786.webp',
				'/images/header-carousel/slide-1-786.jpg',
				'/images/header-carousel/slide-1-576.webp',
				'/images/header-carousel/slide-1-576.jpg',
				// '/images/header-carousel/slide-1-360.webp',
				// '/images/header-carousel/slide-1-360.jpg',
			],
		},
		{
			id: 2,
			title: 'HISSI',
			caption: "HAQIQIY GO'ZALLIK",
			images: [
				'/images/header-carousel/slide-2.webp',
				'/images/header-carousel/slide-2.jpg',
				'/images/header-carousel/slide-2-1360.webp',
				'/images/header-carousel/slide-2-1360.jpg',
				'/images/header-carousel/slide-2-1200.webp',
				'/images/header-carousel/slide-2-1200.jpg',
				'/images/header-carousel/slide-2-992.webp',
				'/images/header-carousel/slide-2-992.jpg',
				'/images/header-carousel/slide-2-786.webp',
				'/images/header-carousel/slide-2-786.jpg',
				'/images/header-carousel/slide-2-576.webp',
				'/images/header-carousel/slide-2-576.jpg',
				// '/images/header-carousel/slide-2-360.webp',
				// '/images/header-carousel/slide-2-360.jpg',
			],
		},
		{
			id: 3,
			title: 'UYG’UNLIGI',
			caption: 'BIRLIK',
			images: [
				'/images/header-carousel/slide-3.webp',
				'/images/header-carousel/slide-3.jpg',
				'/images/header-carousel/slide-3-1360.webp',
				'/images/header-carousel/slide-3-1360.jpg',
				'/images/header-carousel/slide-3-1200.webp',
				'/images/header-carousel/slide-3-1200.jpg',
				'/images/header-carousel/slide-3-992.webp',
				'/images/header-carousel/slide-3-992.jpg',
				'/images/header-carousel/slide-3-786.webp',
				'/images/header-carousel/slide-3-786.jpg',
				'/images/header-carousel/slide-3-576.webp',
				'/images/header-carousel/slide-3-576.jpg',
				// '/images/header-carousel/slide-3-360.webp',
				// '/images/header-carousel/slide-3-360.jpg',
			],
		},
		{
			title: 'EKOZONA',
			caption: 'MAXSUS XUSUSIY',
			images: [
				'/images/header-carousel/slide-4.webp',
				'/images/header-carousel/slide-4.jpg',
				'/images/header-carousel/slide-4-1360.webp',
				'/images/header-carousel/slide-4-1360.jpg',
				'/images/header-carousel/slide-4-1200.webp',
				'/images/header-carousel/slide-4-1200.jpg',
				'/images/header-carousel/slide-4-992.webp',
				'/images/header-carousel/slide-4-992.jpg',
				'/images/header-carousel/slide-4-786.webp',
				'/images/header-carousel/slide-4-786.jpg',
				'/images/header-carousel/slide-4-576.webp',
				'/images/header-carousel/slide-4-576.jpg',
				// '/images/header-carousel/slide-4-360.webp',
				// '/images/header-carousel/slide-4-360.jpg',
			],
		},
		{
			title: 'DAVRI',
			caption: 'BILLURDAY YONISH',
			images: [
				'/images/header-carousel/slide-5.webp',
				'/images/header-carousel/slide-5.jpg',
				'/images/header-carousel/slide-5-1360.webp',
				'/images/header-carousel/slide-5-1360.jpg',
				'/images/header-carousel/slide-5-1200.webp',
				'/images/header-carousel/slide-5-1200.jpg',
				'/images/header-carousel/slide-5-992.webp',
				'/images/header-carousel/slide-5-992.jpg',
				'/images/header-carousel/slide-5-786.webp',
				'/images/header-carousel/slide-5-786.jpg',
				'/images/header-carousel/slide-5-576.webp',
				'/images/header-carousel/slide-5-576.jpg',
				// '/images/header-carousel/slide-5-360.webp',
				// '/images/header-carousel/slide-5-360.jpg',
			],
		},
	],
	ru: [
		{
			id: 1,
			title: 'УЮТА',
			caption: 'ОТКРОЙТЕ ЦАРСТВО',
			images: [
				'/images/header-carousel/slide-1.webp',
				'/images/header-carousel/slide-1.jpg',
				'/images/header-carousel/slide-1-1360.webp',
				'/images/header-carousel/slide-1-1360.jpg',
				'/images/header-carousel/slide-1-1200.webp',
				'/images/header-carousel/slide-1-1200.jpg',
				'/images/header-carousel/slide-1-992.webp',
				'/images/header-carousel/slide-1-992.jpg',
				'/images/header-carousel/slide-1-786.webp',
				'/images/header-carousel/slide-1-786.jpg',
				'/images/header-carousel/slide-1-576.webp',
				'/images/header-carousel/slide-1-576.jpg',
				// '/images/header-carousel/slide-1-360.webp',
				// '/images/header-carousel/slide-1-360.jpg',
			],
		},
		{
			id: 2,
			title: 'КРАСОТЫ',
			caption: 'ЧУВСТВО ИСТИННОЙ',
			images: [
				'/images/header-carousel/slide-2.webp',
				'/images/header-carousel/slide-2.jpg',
				'/images/header-carousel/slide-2-1360.webp',
				'/images/header-carousel/slide-2-1360.jpg',
				'/images/header-carousel/slide-2-1200.webp',
				'/images/header-carousel/slide-2-1200.jpg',
				'/images/header-carousel/slide-2-992.webp',
				'/images/header-carousel/slide-2-992.jpg',
				'/images/header-carousel/slide-2-786.webp',
				'/images/header-carousel/slide-2-786.jpg',
				'/images/header-carousel/slide-2-576.webp',
				'/images/header-carousel/slide-2-576.jpg',
				// '/images/header-carousel/slide-2-360.webp',
				// '/images/header-carousel/slide-2-360.jpg',
			],
		},
		{
			id: 3,
			title: 'ГАРМОНИИ',
			caption: 'ЕДИНСТВО',
			images: [
				'/images/header-carousel/slide-3.webp',
				'/images/header-carousel/slide-3.jpg',
				'/images/header-carousel/slide-3-1360.webp',
				'/images/header-carousel/slide-3-1360.jpg',
				'/images/header-carousel/slide-3-1200.webp',
				'/images/header-carousel/slide-3-1200.jpg',
				'/images/header-carousel/slide-3-992.webp',
				'/images/header-carousel/slide-3-992.jpg',
				'/images/header-carousel/slide-3-786.webp',
				'/images/header-carousel/slide-3-786.jpg',
				'/images/header-carousel/slide-3-576.webp',
				'/images/header-carousel/slide-3-576.jpg',
				// '/images/header-carousel/slide-3-360.webp',
				// '/images/header-carousel/slide-3-360.jpg',
			],
		},
		{
			title: 'ЭКО ЗОНА',
			caption: 'ОСОБАЯ ПРИВАТНАЯ',
			images: [
				'/images/header-carousel/slide-4.webp',
				'/images/header-carousel/slide-4.jpg',
				'/images/header-carousel/slide-4-1360.webp',
				'/images/header-carousel/slide-4-1360.jpg',
				'/images/header-carousel/slide-4-1200.webp',
				'/images/header-carousel/slide-4-1200.jpg',
				'/images/header-carousel/slide-4-992.webp',
				'/images/header-carousel/slide-4-992.jpg',
				'/images/header-carousel/slide-4-786.webp',
				'/images/header-carousel/slide-4-786.jpg',
				'/images/header-carousel/slide-4-576.webp',
				'/images/header-carousel/slide-4-576.jpg',
				// '/images/header-carousel/slide-4-360.webp',
				// '/images/header-carousel/slide-4-360.jpg',
			],
		},
		{
			title: 'БЛЕСКОМ',
			caption: 'ВРЕМЯ СИЯТЬ',
			images: [
				'/images/header-carousel/slide-5.webp',
				'/images/header-carousel/slide-5.jpg',
				'/images/header-carousel/slide-5-1360.webp',
				'/images/header-carousel/slide-5-1360.jpg',
				'/images/header-carousel/slide-5-1200.webp',
				'/images/header-carousel/slide-5-1200.jpg',
				'/images/header-carousel/slide-5-992.webp',
				'/images/header-carousel/slide-5-992.jpg',
				'/images/header-carousel/slide-5-786.webp',
				'/images/header-carousel/slide-5-786.jpg',
				'/images/header-carousel/slide-5-576.webp',
				'/images/header-carousel/slide-5-576.jpg',
				// '/images/header-carousel/slide-5-360.webp',
				// '/images/header-carousel/slide-5-360.jpg',
			],
		},
	],
}
